url: "https://ikanlid.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "academic" # the subpath of your site, e.g. /blog
collections:
  authors:
    output: true 
title: "academic" # the name of your site, e.g. ACME Corp.
description: "a Jekyll theme for academia"

collections:
  pois:
    output: true