menu:
- {name: 'Η Ομάδα', url: '/people'}
- {name: 'Η Εργασία', url: '/publications'}
- {name: 'Οι Λίμνες', url: '/lakesingreece'}
- {name: 'Επικοινωνία', url: '/contact'}

people:
- {name: 'Σπυρίδων Μαυρομάτης', title: 'Μεταπτυχιακός Φοιτητής', department: 'Τμήμα Πληροφορικής', institution: 'Ιόνιο Πανεπιστήμιο', institution_address: 'Κέρκυρα', phone: '(000) 000-0000', email: 'inf.dig2201@ionio.gr', office: 'Science Building 505', image: 'assets/img/spiros-mavromatis.jpeg', url: 'primary-investigator'}
- {name: 'Ιωάννα Κανλίδου', title: 'Μεταπτυχιακός Φοιτητής', department: 'Τμήμα Πληροφορικής', institution: 'Ιόνιο Πανεπιστήμιο', institution_address: 'Κέρκυρα', phone: '(000) 000-0000', email: 'inf.dig2204@ionio.gr', office: 'Science Building 505', image: 'assets/img/ioanna-kanlidou.jpeg', url: 'lab-technician'}
- {name: 'Νικολέτα Τρύφωνα', title: 'Μεταπτυχιακός Φοιτητής', department: 'Τμήμα Πληροφορικής', institution: 'Ιόνιο Πανεπιστήμιο', institution_address: 'Κέρκυρα', phone: '(000) 000-0000', email: 'inf.dig2207@ionio.gr', office: 'Science Building 505', image: 'assets/img/nicole-tryfona.jpeg', url: 'graduate-student'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/LeNPaul'}
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}

contacts:
- {name: 'Dr. Academia', title: 'Professor', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
